### ISSUE TITLE
有关colab上测试报错G_synthesis/_Run/concat:0的建议

### ISSUE THREAD

**Issue by jjandnn** [a312863063/seeprettyface-face_editor#2]
在colab上测试。

报错是：
……
KeyError: "The name 'G_synthesis_1/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis_1/_Run/concat', does not exist in the graph."

During handling of the above exception, another exception occurred:

……
KeyError: "The name 'G_synthesis/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis/_Run/concat', does not exist in the graph."

请遇到这个问题的小伙伴统一修改unit目录中的generator_model.py文件
将generator类中：
        try:
            self.generator_output = self.graph.get_tensor_by_name('G_synthesis_1/_Run/concat:0')
        except KeyError:
            # If we loaded only Gs and didn't load G or D, then scope "G_synthesis_1" won't exist in the graph.
            self.generator_output = self.graph.get_tensor_by_name('G_synthesis/_Run/concat:0')

修改为：
        try:
            self.generator_output = self.graph.get_tensor_by_name('G_synthesis_1/_Run/concat/concat:0')
        except KeyError:
            # If we loaded only Gs and didn't load G or D, then scope "G_synthesis_1" won't exist in the graph.
            self.generator_output = self.graph.get_tensor_by_name('G_synthesis/_Run/concat:0')

供楼主参考。

**Comment by lincong666** [comment]
> 在colab上测试。
> 
> 报错是：
> ……
> KeyError: "The name 'G_synthesis_1/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis_1/_Run/concat', does not exist in the graph."
> 
> During handling of the above exception, another exception occurred:
> 
> ……
> KeyError: "The name 'G_synthesis/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis/_Run/concat', does not exist in the graph."
> 
> 请遇到这个问题的小伙伴统一修改unit目录中的generator_model.py文件
> 将generator类中：
> try:
> self.generator_output = self.graph.get_tensor_by_name('G_synthesis_1/_Run/concat:0')
> except KeyError:
> # If we loaded only Gs and didn't load G or D, then scope "G_synthesis_1" won't exist in the graph.
> self.generator_output = self.graph.get_tensor_by_name('G_synthesis/_Run/concat:0')
> 
> 修改为：
> try:
> self.generator_output = self.graph.get_tensor_by_name('G_synthesis_1/_Run/concat/concat:0')
> except KeyError:
> # If we loaded only Gs and didn't load G or D, then scope "G_synthesis_1" won't exist in the graph.
> self.generator_output = self.graph.get_tensor_by_name('G_synthesis/_Run/concat:0')
> 
> 供楼主参考。

what the unit directory？

**Comment by eeewhe** [comment]
util folder
