### ISSUE TITLE
对于任意输入图片获取latent的方法

### ISSUE THREAD

**Issue by zhangqijun** [a312863063/seeprettyface-face_editor#3]
我们现在使用的是  [pbaylies/stylegan-encoder](https://github.com/pbaylies/stylegan-encoder) 的方法，但是获取一张图片的latent太慢了。看您的博客曾经介绍过BiGAN的方法获取latent，不知效果如何。

**Comment by sky186** [comment]
@a312863063 
Hi,
Is the face attribution the same as the face generator model?
There is no model download address for this project。
And your train process and code is the styleGan_tensorflow?

**Comment by a312863063** [comment]
> 我们现在使用的是 [pbaylies/stylegan-encoder](https://github.com/pbaylies/stylegan-encoder) 的方法，但是获取一张图片的latent太慢了。看您的博客曾经介绍过BiGAN的方法获取latent，不知效果如何。

哈喽～觉得慢有可能是因为编码器在训练时使用的是高质量的清晰图片，而在测试时使用的是不清晰的真实图片，之后为了找到准确定位不得已得进一步微调耗费时间吧。有没有尝试过在预训练时使用不清晰的图片做编码呢？

**Comment by Young1403** [comment]
@a312863063 你好，请问你是如何把从网上爬得图片进行分辨率提升用于stylegan训练的？我想多用一些数据重新训练stylegan，但是网上爬得图片太小，希望能得到指点，谢谢！

**Comment by BZbyr** [comment]
这个可以迁移到动漫图像上吗？

**Comment by PHI6kai** [comment]
@zhangqijun 您好，想问一下您是如何使用[pbaylies/stylegan-encoder](https://github.com/pbaylies/stylegan-encoder)进行获取的？我只看到代码里面是对齐后生成融合图片，没有看到latent的步骤

**Comment by zhangqijun** [comment]
> @zhangqijun 您好，想问一下您是如何使用[pbaylies/stylegan-encoder](https://github.com/pbaylies/stylegan-encoder)进行获取的？我只看到代码里面是对齐后生成融合图片，没有看到latent的步骤

encode_images.py 就是获取latent
